# Generated by Django 3.1.5 on 2021-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField(max_length=250)),
                ('max_delivery_time', models.CharField(default='1 Week', max_length=250)),
                ('product_photo', models.ImageField(upload_to='images')),
                ('units_available', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
