# Generated by Django 3.1.5 on 2021-01-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210122_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
    ]
