# Generated by Django 3.1.5 on 2021-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.JSONField(null=True),
        ),
    ]
